### ISSUE TITLE
Create variables for Azure Service Fabric cluster endpoints

### ISSUE THREAD

**Issue by Phydeauxman** [f5devcentral/f5-azure-saca#101]
The ARM templates have values that are hard coded for Azure Government. The concatenated values in the `failoverCmdArray` variable and the `commandToExecute` parameter use the hard coded value of `.cloudapp.usgovcloudapi.net` which is the endpoint for Azure Government.

Suggest making a parameter for this that can take an input and has a default value.

Azure Government = *.cloudapp.usgovcloudapi.net
Azure Commercial = *.cloudapp.azure.com

Switching to variables for this value will also make the code portable to other environments
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide

**Comment by Mikej81** [comment]
resolved in PR #105
