### ISSUE TITLE
Make subnets into parameters and integrate AS3 file update with deployment

### ISSUE THREAD

**Issue by Phydeauxman** [f5devcentral/f5-azure-saca#102]
Most customers would need to use an assigned IP range for the different subnets used in the SACA architecture. This IP range will likely differ from what is in the ARM templates and AS3 files.

Recommend creating a parameters file with the different subnets parameters an removing the default values from the parameter declarations.

Incorporating a dynamic updating of the AS3 file to be used with the correct IP addresses based on the subnets the user entered would an additional manual step in preparing to files for the deployment

**Comment by Mikej81** [comment]
Generally this is done by our Professional Services and discussed as part of the SOW, but open to suggestions to streamline.

**Comment by Mikej81** [comment]
Parameterized subnets, and templatized AS3/DO have been built into the terraform version of SACA (SACAv3), available here:  [https://github.com/Mikej81/terraform-azure-f5-scca](https://github.com/Mikej81/terraform-azure-f5-scca)

Currently working on cleanup on 3-Tier then repo will be moved over to F5 Org.
