### ISSUE TITLE
Template Validation Error after recent change

### ISSUE THREAD

**Issue by f4plusplus** [f5devcentral/f5-azure-saca#104]
"additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 323,
        "linePosition": 128,
        "path": "variables.cloudPath"
      }

Deployment template validation failed: 'The template variable 'cloudPath' is not valid: The provided arguments for template language function 'if' is not valid: all arguments should be of type 'boolean'. Please see https://aka.ms/arm-template-expressions#if for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.'. (Code: InvalidTemplate)

I get this error every time I try to deploy the commercial, PAYG, 1 Tier version.  This is the version we are using for Agility in 8 days.  We deployed 60 instances of this 2 weeks ago with no issues.  I think this is due to adding the Commercial or Govt option in the Template.

**Comment by Mikej81** [comment]
fix in PR #105
