### ISSUE TITLE
Cannot reach jmpbox

### ISSUE THREAD

**Issue by svbfromnl** [f5devcentral/f5-azure-saca#107]
The only way for me to reach into this environment after it's deployed is by adding a new public ip, and attaching it to -mgmt3 nic, followed by adding an inbound rule to the security group. 
If that's not it, what is the intended traffic flow to get to either the bigip managemnt console or the jump box(es)?

**Comment by Mikej81** [comment]
SSH or RDP to the PIP that is created.  You can see the SSH and RDP policies that will be created in the base AS3 declaration:  [https://github.com/f5devcentral/f5-azure-saca/blob/master/SACAv2/AS3/sccaBaseline.json#L22](https://github.com/f5devcentral/f5-azure-saca/blob/master/SACAv2/AS3/sccaBaseline.json#L22)

Are you using the default ARM and AS3 or have you modified anything?

**Comment by svbfromnl** [comment]
I tried to connect to -ext-pip0. Both the SSH and the RDP time out. 

I'm deploying straight from the GitHub page into my commercial Azure. No changes at all.

**Comment by Mikej81** [comment]
The template defaults to government cloud, make sure to select the commercial cloud on the initial drop down.  

Are you changing any of the default values for provisioning?  If the modules are not provisioned properly for the AS3 thats deployed, then the AS3 may fail.

You can access the console from Azure Portal and send any errors you find.

**Comment by svbfromnl** [comment]
I deployed before you added the [cloudSelector dropdown](https://github.com/f5devcentral/f5-azure-saca/commit/18e79f50d5f27c4c29a321867924e84cec04f7a1#diff-4a9831ae81009b936136f3621f396374). After scrapping my resource group and redeploying again (and selecting false), I can now use -ext-pip0 as designed.
