### ISSUE TITLE
governmentCloudRegion needs updated description

### ISSUE THREAD

**Issue by svbfromnl** [f5devcentral/f5-azure-saca#108]
`"parameters": {
        "governmentCloudRegion": {
            "defaultValue": true,
            "metadata": {
                "description": "Type of authentication to use on the Virtual Machine, password based authentication or key based authentication."
            },
            "type": "bool"
        }`

This is part of the commercial deployment script. If it does belong here, what does it do?

**Comment by Mikej81** [comment]
This is a selectable option when you deploy the template, how are you deploying the templates?  If you are not deploying in the US Government Cloud region, the governmentCloudRegion value should be false.  These templates were specifically designed for the US Government regions.

You can find stdout and stderr logs under /var/log/cloud/azure on the big-ip.  

The description does need to be updated in the template to properly reflect the value.
