### ISSUE TITLE
Getting an error about missing variable

### ISSUE THREAD

**Issue by sewalshmsft** [f5devcentral/f5-azure-saca#124]
Should this line use bigip_regkey instead of license for the variable declaration that is getting passed to the DO? 

https://github.com/f5devcentral/f5-azure-saca/blob/7f369b9ee358dfbdfda72b7cceb71bfc1cefab35/three_tier/waf/bigip.tf#L374

The DO requires ${bigip_regKey} as an input for the variable, not ${license}. 

https://github.com/Mikej81/f5-bigip-hardening-DO/blob/5f3563afabf730e3851a83734fdf18cb689b9c1c/dist/terraform/latest/byol_cluster_waf_tier.json#L12

**Comment by Mikej81** [comment]
Patched in DO Repo.  [https://github.com/Mikej81/f5-bigip-hardening-DO/commit/5ae8236d60e5dbb8cd7f038999d3e66ad38046d2](https://github.com/Mikej81/f5-bigip-hardening-DO/commit/5ae8236d60e5dbb8cd7f038999d3e66ad38046d2)

**Comment by sewalshmsft** [comment]
These two lines in the firewall.tf use bigip_regkey,, these will need updating too:

https://github.com/f5devcentral/f5-azure-saca/blob/7f369b9ee358dfbdfda72b7cceb71bfc1cefab35/three_tier/firewall/bigip.tf#L413

https://github.com/f5devcentral/f5-azure-saca/blob/7f369b9ee358dfbdfda72b7cceb71bfc1cefab35/three_tier/firewall/bigip.tf#L440

**Comment by Mikej81** [comment]
patched in commit commit 4f2373caf673a1bdb88bbc7ad86bbde108e6d7ff
