### ISSUE TITLE
These two lines in the firewall/bigip.tf use bigip_regkey, these will need updating too:

### ISSUE THREAD

**Issue by sewalshmsft** [f5devcentral/f5-azure-saca#125]
These two lines in the firewall/bigip.tf use bigip_regkey, these will need updating too:

https://github.com/f5devcentral/f5-azure-saca/blob/7f369b9ee358dfbdfda72b7cceb71bfc1cefab35/three_tier/firewall/bigip.tf#L413

https://github.com/f5devcentral/f5-azure-saca/blob/7f369b9ee358dfbdfda72b7cceb71bfc1cefab35/three_tier/firewall/bigip.tf#L440

_Originally posted by @sewalshmsft in https://github.com/f5devcentral/f5-azure-saca/issues/124#issuecomment-740741420_

**Comment by sewalshmsft** [comment]
I see the byol_waf_cluster.json and byol_cluster.json were using different inputs.

**Comment by Mikej81** [comment]
Vars were changed to match across the board.
