### ISSUE TITLE
Declarative Onboarding isn't working with BYOL

### ISSUE THREAD

**Issue by sewalshmsft** [f5devcentral/f5-azure-saca#129]
I'm running basically the as-provided variables.tf, only changing the username/password and setting it to single tier deployment. 

It looks like there's a bad character when outputting the declarative onboarding script when it executes as part of the Azure custom script extension at startup. 

I've attached the startup log and the output JSONs in a zip to help you troubleshoot:
[startup-script.zip](https://github.com/f5devcentral/f5-azure-saca/files/5928070/startup-script.zip)

**Comment by Mikej81** [comment]
We have identified a bug in terraform 0.14.5 in Windows, does that match your environment?  Seems there is ^M being added for CRLF on windows boxes.  

Are you using the latest 3.0.2?  We added a workaround to stream the characters out of the files.

**Comment by Mikej81** [comment]
Ah, its removing the $schema attribute from the DO causing the failure.  What version of TF are you using and on what OS?  Are you using the powershell terminal or git-bash?

**Comment by sewalshmsft** [comment]
Thanks for the quick response Mike. I'm running TF 0.13.5 on Windows 10. PowerShell terminal through Visual Code.

**Comment by Mikej81** [comment]
We have been noticing some odd behavior lately with windows machines.  Ill see if I can figure out a workaround.

**Comment by Mikej81** [comment]
@sewalshmsft closing out, patched in DO / AS3 repos.  Removed $Schema attributes from declarations.  Should run now, tested good.

**Comment by sewalshmsft** [comment]
Thanks Mike, I had a good deploy with TF 0.14.5 + git-bash on Windows 10.
