### ISSUE TITLE
files not found for Custom Script extension when choosing PUA

### ISSUE THREAD

**Issue by mikeoleary** [f5devcentral/f5-azure-saca#37]
When I deploy SACAv2 with PUA, I get the following error:

        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'start'. Error message: \"Enable failed: processing file downloads failed: failed to download file[5]: failed to download file: unexpected status code: got=404 expected=200\"."

Looking further it looks like these fileUris may have broken links ready to update

"https://raw.githubusercontent.com/billchurch/f5-pua/master/bin/build_pua.sh",
 "https://raw.githubusercontent.com/Mikej81/f5-azure-saca/SACAv2/3NIC%201Tier%20HA%20with%20PUA/dataSource.php"

**Comment by Mikej81** [comment]
PUA public repo being pulled offline, probably need to remove this template and link...

**Comment by Mikej81** [comment]
Removed PUA options and artifacts, closing issue.
