### ISSUE TITLE
F5 VM deletes itself after deployment

### ISSUE THREAD

**Issue by rjohnson318** [f5devcentral/f5-azure-saca#78]
After a successful deployment of the SACAv2 Azure Government Tier 1, the first f5 VM deletes itself automatically. I have tried deploying this 4x with the same result each time. Also, I cannot access the F5 frontend at all, it just times out. The management network is not the value I set it to be aswell. Any help would be great, thank you.

**Comment by F5Rob** [comment]
I am onsite with the customer and we deployed the BIG-IPs via the marketplace manually and configured the environment manually.

**Comment by Mikej81** [comment]
I have not been able to recreate this issue.  Going to close.  If the issue happens again and can be recreated please re-open.
