### ISSUE TITLE
Conflict error after deployment

### ISSUE THREAD

**Issue by AugWin** [f5devcentral/f5-azure-saca#80]
Getting this error when deploying:
{ "id": "/subscriptions/a0b713be-1237-4769-8647-f0f281a998c9/resourceGroups/AW_ResGroup/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/1A57531F9F9E51E9", "operationId": "1A57531F9F9E51E9", "properties": { "provisioningOperation": "Create", ### "provisioningState": "Failed", "timestamp": "2019-09-27T17:14:29.7262626Z", "duration": "PT50.775008S", "trackingId": "6cf492bd-7f97-487a-be25-134306fba701", **"statusCode": "Conflict"**, "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'start'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\nabout to execute\nchecking mcpd\nmcpd ready\nloading verifyHash script\nLoading configuration...\n /config/verifyHash\nloaded verifyHash\n**verifying /config/cloud/f5-cloud-libs.tar.gz\n/config/cloud/f5-cloud-libs.tar.gz is not valid**\n\n[stderr]\nscript did not successfully complete, status:1\n/bin/sh: line 36: /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs/scripts/util.sh: No such file or directory\n\"." } ] } }, "targetResource": { "id": "/subscriptions/a0b713be-1237-4769-8647-f0f281a998c9/resourceGroups/AW_ResGroup/providers/Microsoft.Compute/virtualMachines/awdns-awf5vm1/extensions/start", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "awdns-awf5vm1/start" } }}

**Comment by Mikej81** [comment]
Need more details.
-Which Template?  
-Are you using the most recent or from an old clone?
-Are you using Click to Deploy button or Copy Paste Json?

The error is pointing out that the Cloud Libs & hash is not valid so its halting deployment.

**Comment by AugWin** [comment]
SACAv2 1-tier - most recent, click to deploy

**Comment by Mikej81** [comment]
F5 updated the cloud-libs library 2 days ago, updated the hash and file location so this wont happen again.  Give it a try now.

**Comment by AugWin** [comment]
Sorry took awhile to get cycles to test.  It works fine now thanks!
