### ISSUE TITLE
Commercial Cloud FQDN is hard-coded in the AzureDeploy.json

### ISSUE THREAD

**Issue by jstaley22** [f5devcentral/f5-azure-saca#83]
I noticed that the commercial cloud is hard coded in mutliple places in the template which produces the wrong VM name when deploying the template to MAG. I deployed the 1 Tier file but the 3 Tier file also looks wrong.
 
Correct URL Name should be ‘cloudapp.usgovcloudapi.net’ instead of ‘cloudapp.azure.com’. Probably need to have a GovCloud check or parameter to adjust the name for commercial or govcloud depending on deployment scenario.
 
Files:
https://github.com/f5devcentral/f5-azure-saca/blob/master/SACAv2/3NIC_1Tier_HA/azureDeploy.json
https://github.com/f5devcentral/f5-azure-saca/blob/master/SACAv2/3NIC_3Tier_HA/azureDeploy.json

**Comment by Mikej81** [comment]
These URL's are only used in via API failover, the current SACA design uses via LB failover.  URLs have been updated in #84 and #85 via Kyle H at MS.
