### ISSUE TITLE
Enable Accelerated Networking in SACA ARM templates

### ISSUE THREAD

**Issue by AugWin** [f5devcentral/f5-azure-saca#86]
This is supported on TMOS v15+ and we need to enable this for SACA templates so customers can use higher-throughput VEs in their SACA deployments.

Ref - https://clouddocs.f5networks.net/cloud/public/v1/azure/Azure_accelNet.html#azureaccelnet

Thanks,
August

**Comment by Mikej81** [comment]
patched in #87

**Comment by Mikej81** [comment]
Just a side note that changing the tmos version to 15.x is required for Accelerated Networking to work.  I will add logic to detect the correct version in a new patch.
