### ISSUE TITLE
DNS prefix used as part of Windows Jump Box Name

### ISSUE THREAD

**Issue by f4plusplus** [f5devcentral/f5-azure-saca#98]
![error](https://user-images.githubusercontent.com/39102771/79409233-691da480-7f6b-11ea-8ef4-8e56452c632e.png)

Attached is a picture of the error with a DNS prefix that is 5 characters long.  it made the computer name 16 characters long and it generated an error.  We should test the length and truncate.

**Comment by Mikej81** [comment]
This is a known *issue*.  There is a length() string function in ARM templates.  Its also possible just to hardcode the Windows Jumpbox name instead of using the dnsLabel.

**Comment by Mikej81** [comment]
resolved in pr #105
